### ISSUE TITLE
how do you use this on windows 

### ISSUE THREAD

**Issue by Cxsmo-ai** [floe/backscrub#162] opened 2023-04-02 09:21 UTC
how do you use this on windows

**Comment by floe** [comment] 2023-04-02 10:20
Duplicate of #92 & #97.

**Closed as completed by floe** 2023-04-02 10:20 UTC

**Comment by Cxsmo-ai** [comment] 2023-04-03 02:01
there is this but they don't say how to use it at all https://github.com/phlash/obs-backscrub if some can help me get this to work that would be great
